mysocialmedia/app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('reels/',views.reels,name='reels'),
    path('signup/',views.usersignup,name='user_signup'),
    path('login/',views.userlogin,name='user_login'),
    path('logout/',views.userlogout,name='user_logout'),
    path('explore/',views.explore,name='explore'),
    path('addpost/',views.addpost,name='addpost'),
    path('addreels/',views.addreels,name='addreels'),
    path('fup/',views.followeduserprofile,name='fup'),
    path('myprofile/',views.myprofile,name='myprofile'),
    path('up/',views.userprofile,name='up'),

]

mysocialmedia/mysocialmedia/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]

mysocialmedia/app1/models.py
from django.db import models

# Create your models here.

mysocialmedia/app1/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .models import MainCatogory, ProdCatogory, Products, CartItem
# Create your views here.

def home(request):
    return render(request,'home.html')

def reels(request):
    return render(request,'home1.html')

def usersignup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('pass1')
        password2 = request.POST.get('pass2')
        if password1 == password2:
            if User.objects.filter(username=username,email=email).exists():
                messages.info(request,'username alreadt exists!!!')
                print("already have")
                return redirect('SuperMarket1:user_signup')
            else:
                new_user=User.objects.create_user(username,email,password1)
                new_user.save()
                return redirect('SuperMarket1:user_login')
        else:
            print('wrong password')
    return render(request,'signup.html')

def userlogin(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('pass1')
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('app1:all_products')
        else:
            messages.info(request,'user not exist')
            print('user not exist')
            return redirect('app1:user_login')
    return render(request,'login.html')

def userlogout(request):
    logout(request)
    return redirect('app1:user_login')

def explore(request):
    return render(request,'explore.html')

def addpost(request):
    return render(request,'addpost.html')

def addreels(request):
    return render(request,'addreel.html')

def followeduserprofile(request):
    return render(request,'followeduserprofile.html')

def myprofile(request):
    return render(request,'myprofile.html')

def userprofile(request):
    return render(request,'userprofile.html')


mysocialmedia/templates/addpost.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <title>Add_Post_page</title>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="overflow: hidden; position: fixed;top: 0;width: 100%;padding-right: 20px;">
            <div class="container-fluid">
              <a href="{% url 'app1:home' %}"><h2>MySocialMedia</h2></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:explore' %}">Explore</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'app1:addpost' %}">Add Post</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:myprofile' %}">My Profile</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </div>
    <div class="container">
        <div class="row" style="margin-top: 150px;">
          <div class="col">
              <a style="color: black;" href="{% url 'app1:addpost' %}">POSTS</a>
              <a style="margin-left: 25px;" href="{% url 'app1:addreels' %}">REELS</a>
          </div>
        </div>
          <div class="row"style="margin-top: 50px;">
              <div class="col">
                <h3>Upload Post</h3>
                <form action="#post" enctype="multipart/form-data" method="post">
                    <button type="submit">Upload</button>
                </form>
              </div>
          </div>
    </div>



    <div class="container-fluid" style="margin-top: 30px;background-color: rgb(1, 1, 73);height: 150px;">
      <div class="row">
          <div class="col" style="text-align: center;margin-top: 20px;">
              <a style="color: white;margin: 25px;" href="">Career</a>
              <a style="color: white;margin: 25px;" href="">Family</a>
              <a style="color: white;margin: 25px;" href="">Bussiness</a>
              <a style="color: white;margin: 25px;" href="">Website</a>
              <a style="color: white;margin: 25px;" href="">Journy</a>
              <a style="color: white;margin: 25px;" href="">About Us</a>
              <a style="color: white;margin: 25px;" href="">Contact Us</a>
              <a style="color: white;margin: 25px;" href="">Terms & Conditions</a>
          </div>
      </div>
      <div class="row">
          <div class="col" style="text-align: center;margin-top: 20px;color: white;">
              <p>all the rights are personalised </p>
          </div>
      </div>
  </div>


  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>  
</body>
</html>

mysocialmedia/templates/addreel.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <title>Add_Reel_page</title>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="overflow: hidden; position: fixed;top: 0;width: 100%;padding-right: 20px;">
            <div class="container-fluid">
              <a href="{% url 'app1:home' %}"><h2>MySocialMedia</h2></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:explore' %}">Explore</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'app1:addpost' %}">Add Post</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:myprofile' %}">My Profile</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </div>
    <div class="container">
        <div class="row" style="margin-top: 150px;">
            <div class="col">
                <a href="{% url 'app1:addpost' %}">POSTS</a>
                <a style="margin-left: 25px;color: black;" href="{% url 'app1:addreels' %}">REELS</a>
            </div>
        </div>
        <div class="row"style="margin-top: 50px;">
            <div class="col">
                <h3>Upload Post</h3>
                <form action="#reel" enctype="multipart/form-data" method="post">
                    <button type="submit">Upload</button>
                </form>
            </div>
        </div>
    </div>



    <div class="container-fluid" style="margin-top: 30px;background-color: rgb(1, 1, 73);height: 150px;">
      <div class="row">
          <div class="col" style="text-align: center;margin-top: 20px;">
              <a style="color: white;margin: 25px;" href="">Career</a>
              <a style="color: white;margin: 25px;" href="">Family</a>
              <a style="color: white;margin: 25px;" href="">Bussiness</a>
              <a style="color: white;margin: 25px;" href="">Website</a>
              <a style="color: white;margin: 25px;" href="">Journy</a>
              <a style="color: white;margin: 25px;" href="">About Us</a>
              <a style="color: white;margin: 25px;" href="">Contact Us</a>
              <a style="color: white;margin: 25px;" href="">Terms & Conditions</a>
          </div>
      </div>
      <div class="row">
          <div class="col" style="text-align: center;margin-top: 20px;color: white;">
              <p>all the rights are personalised </p>
          </div>
      </div>
  </div>


  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>  
</body>
</html>

mysocialmedia/templates/followeduserprofile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <title>User_Profile_page</title>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="overflow: hidden; position: fixed;top: 0;width: 100%;padding-right: 20px;">
            <div class="container-fluid">
              <a href="{% url 'app1:home' %}"><h2>MySocialMedia</h2></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link " href="{% url 'app1:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:explore' %}">Explore</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:addpost' %}">Add Post</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:myprofile' %}">My Profile</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </div>
    <div class="container">
        <div class="row" style="margin-top: 150px;padding: 25px;">
            <div class="col col-sm-2">
                <img src="../image/hallo.png" class="img-fluid" alt="p" width="150px" height="250px" style="border: 1px solid gray;border-radius: 70px;">
            </div>
            <div class="col">
                <div class="row">
                    <div class="col">
                        <h3>Username</h3>
                    </div>
                    <div class="col" style="margin-top: 20px;">
                        <a href="">Chat</a>
                        <a style="margin: 15px;" href="{% url 'app1:up' %}">UnFollow</a>
                    </div>
                </div>
                <div class="row" style="margin-top: 20px;">
                    <div class="col">
                        <h6>Full Name</h6>
                        <p>discription</p>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="container-fluid" style="margin-top: 30px;background-color: rgb(1, 1, 73);height: 150px;">
        <div class="row">
            <div class="col" style="text-align: center;margin-top: 20px;">
                <a style="color: white;margin: 25px;" href="">Career</a>
                <a style="color: white;margin: 25px;" href="">Family</a>
                <a style="color: white;margin: 25px;" href="">Bussiness</a>
                <a style="color: white;margin: 25px;" href="">Website</a>
                <a style="color: white;margin: 25px;" href="">Journy</a>
                <a style="color: white;margin: 25px;" href="">About Us</a>
                <a style="color: white;margin: 25px;" href="">Contact Us</a>
                <a style="color: white;margin: 25px;" href="">Terms & Conditions</a>
            </div>
        </div>
        <div class="row">
            <div class="col" style="text-align: center;margin-top: 20px;color: white;">
                <p>all the rights are personalised </p>
            </div>
        </div>
    </div>











    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

mysocialmedia/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <title>Home_page</title>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="overflow: hidden; position: fixed;top: 0;width: 100%;padding-right: 20px;">
            <div class="container-fluid">
              <a href="{% url 'app1:home' %}"><h2>MySocialMedia</h2></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'app1:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:explore' %}">Explore</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:addpost' %}">Add Post</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:user_login' %}">Login/SignUp</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:myprofile' %}">My Profile</a>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </div>
    <div class="container" style="margin-top: 150px;text-align: center;">
        <div class="row">
            <div class="col">
                <a href="{% url 'app1:home' %}">POSTS</a>
                <a style="margin-left: 25px;" href="{% url 'app1:reels' %}">REELS</a>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="row" style="padding: 10px;">
                    <div class="col" style="background-color:black;border-radius: 20px;margin-left: 50px;margin-right: 50px;">        
                        <div class="row">
                            <div class="col" style="margin: 8px;">
                                <img src="../image/hallo.png" class="img-fluid" alt="p" style="width:65px;height:65px;border: 1px solid gray;border-radius: 40px;">
                            </div>
                            <div class="col" style="text-align: center;margin: 25px;">
                                <a style="margin-top: 17px;color: aliceblue;" href="{% url 'app1:fup' %}"><h6>Username</h6></a>
                            </div>
                            <div class="col" style="text-align: right;margin:15px;">
                                <a style="color: aliceblue;" href=""><h3>:::</h3></a>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col" style="background-color: black;margin: 15px;border-radius: 20px;">
                        <div class="Upost"  style="height:500px;text-align: center;padding: 10px;">
                            <img src="../image/hallo.png" class="img-fluid" alt="Post" style="height: 450px;border: 1px solid gray;border-radius: 10px;">
                            <p style="color: aliceblue;">UserName > Discription about post</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col" style="background-color: black;margin-top: 15px;height: 50px;border-top-left-radius: 15px;">
                        <div class="row" style="margin-top: 10px;">
                            <div class="col" style="text-align: left;">
                                <ul>
                                    <li>
                                        <a style="color: aliceblue;" href="">Like</a>
                                    </li>
                                    <li>
                                        <a style="color: aliceblue;" href="">Comment</a>
                                    </li>
                                </ul>
                            </div>
                            
                        </div>
                    </div>
                    <div class="col" style="background-color: black;margin-top: 15px;height: 50px;border-top-right-radius: 15px;">
                        <div class="row" style="margin-top: 10px;text-align: right;margin-right: 15px;">
                            <div class="col">
                                <ul>
                                    <li>
                                        <a style="color: aliceblue;" href="">Share</a>
                                    </li>
                                    <li>
                                        <a style="color: aliceblue;" href="">Save</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid" style="margin-top: 30px;background-color: rgb(1, 1, 73);height: 150px;">
        <div class="row">
            <div class="col" style="text-align: center;margin-top: 20px;">
                <a style="color: white;margin: 25px;" href="">Career</a>
                <a style="color: white;margin: 25px;" href="">Family</a>
                <a style="color: white;margin: 25px;" href="">Bussiness</a>
                <a style="color: white;margin: 25px;" href="">Website</a>
                <a style="color: white;margin: 25px;" href="">Journy</a>
                <a style="color: white;margin: 25px;" href="">About Us</a>
                <a style="color: white;margin: 25px;" href="">Contact Us</a>
                <a style="color: white;margin: 25px;" href="">Terms & Conditions</a>
            </div>
        </div>
        <div class="row">
            <div class="col" style="text-align: center;margin-top: 20px;color: white;">
                <p>all the rights are personalised </p>
            </div>
        </div>
    </div>
































    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

mysocialmedia/templates/home1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <title>Home_page</title>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="width: 100%;padding-right: 20px;">
            <div class="container-fluid">
              <a href="{% url 'app1:home' %}"><h2>MySocialMedia</h2></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'app1:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:explore' %}">Explore</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:addpost' %}">Add Post</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:user_login' %}">Login/SignUp</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:myprofile' %}">My Profile</a>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </div>
    <div class="container" style="margin-top: 20px;text-align: center;">
        <div class="row">
            <div class="col">
                <a href="{% url 'app1:home' %}">POSTS</a>
                <a style="margin-left: 25px;" href="{% url 'app1:reels' %}">REELS</a>
            </div>
        </div>
        <div class="row">
            <div class="col" style="margin-left: 10px;">
                <div class="row" style="padding: 10px;">
                    <div class="col" style="background-color:black;border-radius: 20px;margin-left: 50px;margin-right: 50px;">        
                        <div class="row">
                            <div class="col" style="margin: 8px;">
                                <img src="../image/hallo.png" class="img-fluid" alt="p" style="width:65px;height:65px;border: 1px solid gray;border-radius: 40px;">
                            </div>
                            <div class="col" style="text-align: center;margin: 25px;">
                                <a style="margin-top: 17px;color: aliceblue;" href="{% url 'app1:fup' %}"><h6>Username</h6></a>
                            </div>
                            <div class="col" style="text-align: right;margin:15px;">
                                <a style="color: aliceblue;" href=""><h3>:::</h3></a>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col" style="background-color: black;margin: 15px;border-radius: 20px;">
                        <div class="Upost"  style="height:500px;text-align: center;padding: 10px;">
                            <video autoplay="autoplay" controls="controls" preload="preload" height="450px" width="400px" style="border: 1px solid gray;border-radius: 10px;">
                                <source src="" type="video/mp4"></source>
                            </video>
                            <p style="color: aliceblue;">UserName > Discription about post</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col" style="background-color: black;margin-top: 15px;height: 50px;border-top-left-radius: 15px;">
                        <div class="row" style="margin-top: 10px;">
                            <div class="col" style="text-align: left;">
                                <ul>
                                    <li>
                                        <a style="color: aliceblue;" href="">Like</a>
                                    </li>
                                    <li>
                                        <a style="color: aliceblue;" href="">Comment</a>
                                    </li>
                                </ul>
                            </div>
                            
                        </div>
                    </div>
                    <div class="col" style="background-color: black;margin-top: 15px;height: 50px;border-top-right-radius: 15px;">
                        <div class="row" style="margin-top: 10px;text-align: right;margin-right: 15px;">
                            <div class="col">
                                <ul>
                                    <li>
                                        <a style="color: aliceblue;" href="">Share</a>
                                    </li>
                                    <li>
                                        <a style="color: aliceblue;" href="">Save</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid" style="margin-top: 30px;background-color: rgb(1, 1, 73);height: 150px;">
        <div class="row">
            <div class="col" style="text-align: center;margin-top: 20px;">
                <a style="color: white;margin: 25px;" href="">Career</a>
                <a style="color: white;margin: 25px;" href="">Family</a>
                <a style="color: white;margin: 25px;" href="">Bussiness</a>
                <a style="color: white;margin: 25px;" href="">Website</a>
                <a style="color: white;margin: 25px;" href="">Journy</a>
                <a style="color: white;margin: 25px;" href="">About Us</a>
                <a style="color: white;margin: 25px;" href="">Contact Us</a>
                <a style="color: white;margin: 25px;" href="">Terms & Conditions</a>
            </div>
        </div>
        <div class="row">
            <div class="col" style="text-align: center;margin-top: 20px;color: white;">
                <p>all the rights are personalised </p>
            </div>
        </div>
    </div>
































    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>